name: 'action'

inputs:
  status:
    required: false
    default: 'failure'

  webhookurl:
    required: true

  title:
    required: true

  author:
    required: true

  url:
    required: false

  color:
    required: true

  description:
    required: true

runs:
  using: 'composite'

  steps:
    - name: Send Discord
      shell: bash
      run: |
        DESC = "${{inputs.description}}"
        CONVERT=echo "${DESC//$'\n'/\\n}"
        curl -i -X POST -H "Content-Type: application/json" --data "{\"embeds\": [{\"title\": \"${{inputs.title}}\", \"author\":{\"name\":\"${{inputs.author}}\"},\"color\": \"${{inputs.color}}\",\"description\": \"$CONVERT\"}]}" "${{inputs.webhookurl}}"

